version: '3'
services:
  csvserver:
    image: infracloudio/csvserver:latest
    ports:
      - "9300:9300"
    volumes:
      - ./csvserver/inputFile:/csvserver/inputdata
    env_file:
      - ./csvserver.env 

